name: Upgrade
description: Test PrestaShop upgrade process
runs:
  using: composite
  steps:
    - name: Build docker compose stack
      env:
        VERSION: ${{ matrix.from }}
      shell: bash
      run: |
        bash -c 'if [[ "${VERSION}" == 1.6* ]]; then export BASE_VERSION=7.1-apache; \
        elif [[ "${VERSION}" == 8.* ]]; then export BASE_VERSION=8.1-apache; \
        else export BASE_VERSION=7.2-apache; fi && docker compose up -d'
        bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
    - name: Copy autoupgrade module
      shell: bash
      run: docker exec -u www-data prestashop_autoupgrade cp modules/autoupgrade/ -R admin-dev
    - name: Upgrade (intermediate)
      env:
        CHANNEL: 'archive'
        ARCHIVE_URL: 'https://github.com/PrestaShop/PrestaShop/releases/download/1.7.7.8/prestashop_1.7.7.8.zip'
        XML_URL: 'https://api.prestashop.com/xml/md5/1.7.7.8.xml'
        VERSION: '1.7.7.8'
        FROM: ${{ matrix.from }}
        SKIP: ${{ matrix.ps-versions.channel != 'archive' || !startsWith(matrix.from, '1.6') || startsWith(matrix.ps-versions.version, '1.7.7') }}
      shell: bash
      run: |
        [[ "$SKIP" == true ]] || ${{ github.action_path }}action_upgrade.sh
        [[ "$SKIP" == true ]] || docker stop prestashop_autoupgrade
        [[ "$SKIP" == true ]] || docker rm prestashop_autoupgrade
        [[ "$SKIP" == true ]] || docker run --name prestashop_autoupgrade -p 8001:80 -v autoupgrade_temp-ps:/var/www/html -v "$(pwd):/var/www/html/modules/autoupgrade" --network autoupgrade_default -d prestashop/base:7.2-apache
        [[ "$SKIP" == true ]] || bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "000" ]]; do sleep 5; done'
    - name: Upgrade
      env:
        CHANNEL: ${{ matrix.ps-versions.channel }}
        ARCHIVE_URL: ${{ matrix.ps-versions.zip }}
        XML_URL: ${{ matrix.ps-versions.xml }}
        VERSION: ${{ matrix.ps-versions.version }}
        FROM: ${{ matrix.from }}
      shell: bash
      run: ${{ github.action_path }}action_upgrade.sh
    - name: Check endpoints response
      shell: bash
      run: |
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'
    - name: Rollback
      shell: bash
      run: docker exec -u www-data prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php \
        admin-dev/autoupgrade/cli-rollback.php --dir="admin-dev" \
        --backup=`docker exec prestashop_autoupgrade bash -c "ls -td -- /var/www/html/admin-dev/autoupgrade/backup/*/ | head -n 1 | cut -d'/' -f8 | tr -d '\n'"`;
    - name: Check endpoints response
      shell: bash
      run: |
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'
