name: Upgrade
description: Test PrestaShop upgrade process
runs:
  using: composite
  steps:
    - name: Build docker compose stack
      env:
        VERSION: ${{ matrix.from }}
      shell: bash
      run: |
        bash -c '[[ "${VERSION}" == 1.6* ]] && docker-compose -f docker-compose-7.1.yml up -d || docker-compose -f docker-compose.yml up -d'
        bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
    - name: Copy autoupgrade module
      shell: bash
      run: docker exec -u www-data prestashop_autoupgrade cp modules/autoupgrade/ -R admin-dev
    - name: Upgrade (major)
      env:
        CHANNEL: ${{ matrix.ps-versions.channel }}
        ARCHIVE_URL: ${{ matrix.ps-versions.file }}
        VERSION: ${{ matrix.ps-versions.version }}
        FROM: ${{ matrix.from }}
      shell: bash
      run: ${{ github.action_path }}/action_upgrade.sh
    - name: Check endpoints response
      shell: bash
      run: |
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'
    - name: Rollback
      shell: bash
      run: docker exec -u www-data prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php \
        admin-dev/autoupgrade/cli-rollback.php --dir="admin-dev" \
        --backup=`docker exec prestashop_autoupgrade bash -c "ls -td -- /var/www/html/admin-dev/autoupgrade/backup/*/ | head -n 1 | cut -d'/' -f8 | tr -d '\n'"`;
    - name: Check endpoints response
      shell: bash
      run: |
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
        bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'
