language: php
services: docker

php:
  - '5.6'

env:
  - VERSION=1.7.2.2
    CHANNEL=major
  - VERSION=1.6
    CHANNEL=major
  - VERSION=1.6.1.10
    CHANNEL=minor
  # Check how the upgrade behaves with the latest PrestaShop
  - VERSION=latest
    CHANNEL=minor

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - docker-compose up -d

before_script:
  - bash -c 'while [[ "$(curl -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
  - docker exec -u www-data -ti prestashop_autoupgrade cp modules/autoupgrade/ -R admin-dev

script:
  - php vendor/phpunit/phpunit/phpunit tests

  # PHP Stan
  - if [[ $VERSION == "1.6" ]] || [[ $VERSION == 1\.6* ]]; then
      export PHPSTAN_FILE=phpstan-PS-16.neon;
    else
      export PHPSTAN_FILE=phpstan.neon;
    fi
  - docker run --rm --volumes-from prestashop_autoupgrade -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/web/module/tests/phpstan/$PHPSTAN_FILE;

  # Upgrade
  - docker exec -u www-data -ti prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php admin-dev/autoupgrade/cli-upgrade.php  --dir="admin-dev" --channel="$CHANNEL"
  # Front office -> HTTP code 200 expected (no maintenance)
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
  # Back office -> HTTP code 200 expected
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'

  # Rollback (only when expect a completed upgrade)
  - if [ $VERSION != "latest" ]; then
      docker exec -u www-data -ti prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php admin-dev/autoupgrade/cli-rollback.php  --dir="admin-dev" --backup=`docker exec -ti prestashop_autoupgrade bash -c "ls -td -- /var/www/html/admin-dev/autoupgrade/backup/*/ | head -n 1 | cut -d'/' -f8 | tr -d '\n'"`;
    fi
  # Front office -> HTTP code 200 expected (no maintenance)
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
  # Back office -> HTTP code 200 expected
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'

after_script:
  - docker ps
  - docker logs prestashop_autoupgrade
