language: php
services: docker

php:
  - '7.2'

env:
  - VERSION=latest
    CHANNEL=archive

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - wget https://storage.googleapis.com/prestashop-core-nightly/2020-11-24-1.7.7.x-prestashop_1.7.7.0.zip
  - docker-compose up -d

before_script:
  - bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
  - docker exec -u www-data -ti prestashop_autoupgrade cp modules/autoupgrade/ -R admin-dev
  - docker exec -u www-data -ti prestashop_autoupgrade mkdir admin-dev/autoupgrade/download
  - docker exec -u www-data -ti prestashop_autoupgrade cp modules/autoupgrade/2020-11-24-1.7.7.x-prestashop_1.7.7.0.zip admin-dev/autoupgrade/download/prestashop.zip

script:
  # Upgrade
  - docker exec -u www-data -ti prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php admin-dev/autoupgrade/cli-upgrade.php  --dir="admin-dev" --channel="archive"
  # Front office -> HTTP code 200 expected (no maintenance)
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" == "200" ]'
  # Back office -> HTTP code 200 expected
  - bash -c '[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/admin-dev/index.php)" == "200" ]'

after_script:
  - docker ps
  - docker logs prestashop_autoupgrade
