<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 */

use PHPUnit\Framework\TestCase;
use PrestaShop\Module\AutoUpgrade\Task\Backup\BackupDatabase;
use PrestaShop\Module\AutoUpgrade\UpgradeContainer;

class BackupDatabaseTest extends TestCase
{
    /**
     * @throws Exception
     */
    public function testTablesAreIgnored()
    {
        define('_DB_PREFIX_', 'doge_');

        $container = new UpgradeContainer(__DIR__, __DIR__ . '/..');
        $task = new BackupDatabase($container);

        $tables = json_decode(file_get_contents(__DIR__ . '/../../../fixtures/listOfTablesInDb.json'), true);
        $expectedTables = $this->getExpectedTablesToSync();

        $this->assertEquals($expectedTables, array_values($task->filterTablesToSync($tables)));
    }

    private function getExpectedTablesToSync(): array
    {
        return [
            'doge_access',
            'doge_accessory',
            'doge_address',
            'doge_address_format',
            'doge_admin_filter',
            'doge_advice',
            'doge_advice_lang',
            'doge_alias',
            'doge_attachment',
            'doge_attachment_lang',
            'doge_attribute',
            'doge_attribute_group',
            'doge_attribute_group_lang',
            'doge_attribute_group_shop',
            'doge_attribute_impact',
            'doge_attribute_lang',
            'doge_attribute_shop',
            'doge_authorization_role',
            'doge_badge',
            'doge_badge_lang',
            'doge_carrier',
            'doge_carrier_group',
            'doge_carrier_lang',
            'doge_carrier_shop',
            'doge_carrier_tax_rules_group_shop',
            'doge_carrier_zone',
            'doge_cart',
            'doge_cart_cart_rule',
            'doge_cart_product',
            'doge_cart_rule',
            'doge_cart_rule_carrier',
            'doge_cart_rule_combination',
            'doge_cart_rule_country',
            'doge_cart_rule_group',
            'doge_cart_rule_lang',
            'doge_cart_rule_product_rule',
            'doge_cart_rule_product_rule_group',
            'doge_cart_rule_product_rule_value',
            'doge_cart_rule_shop',
            'doge_category',
            'doge_category_group',
            'doge_category_lang',
            'doge_category_product',
            'doge_category_shop',
            'doge_cms',
            'doge_cms_category',
            'doge_cms_category_lang',
            'doge_cms_category_shop',
            'doge_cms_lang',
            'doge_cms_role',
            'doge_cms_role_lang',
            'doge_cms_shop',
            'doge_condition',
            'doge_condition_advice',
            'doge_condition_badge',
            'doge_configuration',
            'doge_configuration_kpi',
            'doge_configuration_kpi_lang',
            'doge_configuration_lang',
            'doge_contact',
            'doge_contact_lang',
            'doge_contact_shop',
            'doge_country',
            'doge_country_lang',
            'doge_country_shop',
            'doge_currency',
            'doge_currency_shop',
            'doge_customer',
            'doge_customer_group',
            'doge_customer_message',
            'doge_customer_message_sync_imap',
            'doge_customer_thread',
            'doge_customization',
            'doge_customization_field',
            'doge_customization_field_lang',
            'doge_customized_data',
            'doge_date_range',
            'doge_delivery',
            'doge_emailsubscription',
            'doge_employee',
            'doge_employee_shop',
            'doge_fb_category_match',
            'doge_feature',
            'doge_feature_lang',
            'doge_feature_product',
            'doge_feature_shop',
            'doge_feature_value',
            'doge_feature_value_lang',
            'doge_gender',
            'doge_gender_lang',
            'doge_group',
            'doge_group_lang',
            'doge_group_reduction',
            'doge_group_shop',
            'doge_gsitemap_sitemap',
            'doge_homeslider',
            'doge_homeslider_slides',
            'doge_homeslider_slides_lang',
            'doge_hook',
            'doge_hook_alias',
            'doge_hook_module',
            'doge_hook_module_exceptions',
            'doge_image',
            'doge_image_lang',
            'doge_image_shop',
            'doge_image_type',
            'doge_import_match',
            'doge_info',
            'doge_info_lang',
            'doge_info_shop',
            'doge_lang',
            'doge_lang_shop',
            'doge_layered_category',
            'doge_layered_filter',
            'doge_layered_filter_shop',
            'doge_layered_indexable_attribute_group',
            'doge_layered_indexable_attribute_group_lang_value',
            'doge_layered_indexable_attribute_lang_value',
            'doge_layered_indexable_feature',
            'doge_layered_indexable_feature_lang_value',
            'doge_layered_indexable_feature_value_lang_value',
            'doge_layered_price_index',
            'doge_layered_product_attribute',
            'doge_link_block',
            'doge_link_block_lang',
            'doge_link_block_shop',
            'doge_linksmenutop',
            'doge_linksmenutop_lang',
            'doge_log',
            'doge_mail',
            'doge_manufacturer',
            'doge_manufacturer_lang',
            'doge_manufacturer_shop',
            'doge_memcached_servers',
            'doge_message',
            'doge_message_readed',
            'doge_meta',
            'doge_meta_lang',
            'doge_module',
            'doge_module_access',
            'doge_module_carrier',
            'doge_module_country',
            'doge_module_currency',
            'doge_module_group',
            'doge_module_history',
            'doge_module_preference',
            'doge_module_shop',
            'doge_operating_system',
            'doge_order_carrier',
            'doge_order_cart_rule',
            'doge_order_detail',
            'doge_order_detail_tax',
            'doge_order_history',
            'doge_order_invoice',
            'doge_order_invoice_payment',
            'doge_order_invoice_tax',
            'doge_order_message',
            'doge_order_message_lang',
            'doge_order_payment',
            'doge_order_return',
            'doge_order_return_detail',
            'doge_order_return_state',
            'doge_order_return_state_lang',
            'doge_order_slip',
            'doge_order_slip_detail',
            'doge_order_slip_detail_tax',
            'doge_order_state',
            'doge_order_state_lang',
            'doge_orders',
            'doge_pack',
            'doge_page',
            'doge_page_type',
            'doge_page_viewed',
            'doge_pagenotfound',
            'doge_product',
            'doge_product_attachment',
            'doge_product_attribute',
            'doge_product_attribute_combination',
            'doge_product_attribute_image',
            'doge_product_attribute_shop',
            'doge_product_carrier',
            'doge_product_country_tax',
            'doge_product_download',
            'doge_product_group_reduction_cache',
            'doge_product_lang',
            'doge_product_sale',
            'doge_product_shop',
            'doge_product_supplier',
            'doge_product_tag',
            'doge_profile',
            'doge_profile_lang',
            'doge_pscheckout_cart',
            'doge_pscheckout_funding_source',
            'doge_pscheckout_order_matrice',
            'doge_psgdpr_consent',
            'doge_psgdpr_consent_lang',
            'doge_psgdpr_log',
            'doge_quick_access',
            'doge_quick_access_lang',
            'doge_range_price',
            'doge_range_weight',
            'doge_reassurance',
            'doge_reassurance_lang',
            'doge_referrer',
            'doge_referrer_cache',
            'doge_referrer_shop',
            'doge_request_sql',
            'doge_required_field',
            'doge_risk',
            'doge_risk_lang',
            'doge_search_engine',
            'doge_search_index',
            'doge_search_word',
            'doge_sekeyword',
            'doge_shop',
            'doge_shop_group',
            'doge_shop_url',
            'doge_smarty_cache',
            'doge_smarty_last_flush',
            'doge_smarty_lazy_cache',
            'doge_specific_price',
            'doge_specific_price_priority',
            'doge_specific_price_rule',
            'doge_specific_price_rule_condition',
            'doge_specific_price_rule_condition_group',
            'doge_state',
            'doge_stock',
            'doge_stock_available',
            'doge_stock_mvt',
            'doge_stock_mvt_reason',
            'doge_stock_mvt_reason_lang',
            'doge_store',
            'doge_store_lang',
            'doge_store_shop',
            'doge_supplier',
            'doge_supplier_lang',
            'doge_supplier_shop',
            'doge_supply_order',
            'doge_supply_order_detail',
            'doge_supply_order_history',
            'doge_supply_order_receipt_history',
            'doge_supply_order_state',
            'doge_supply_order_state_lang',
            'doge_tab',
            'doge_tab_advice',
            'doge_tab_lang',
            'doge_tab_module_preference',
            'doge_tag',
            'doge_tag_count',
            'doge_tax',
            'doge_tax_lang',
            'doge_tax_rule',
            'doge_tax_rules_group',
            'doge_tax_rules_group_shop',
            'doge_timezone',
            'doge_translation',
            'doge_warehouse',
            'doge_warehouse_carrier',
            'doge_warehouse_product_location',
            'doge_warehouse_shop',
            'doge_web_browser',
            'doge_webservice_account',
            'doge_webservice_account_shop',
            'doge_webservice_permission',
            'doge_zone',
            'doge_zone_shop',
        ];
    }
}
