SET SESSION sql_mode='';
SET NAMES 'utf8mb4';

UPDATE `PREFIX_tab` SET `wording`='Dashboard', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminDashboard' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Sell', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='SELL' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Orders', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentOrders' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Orders', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminOrders' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Invoices', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminInvoices' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Credit Slips', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSlip' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Delivery Slips', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminDeliverySlip' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Shopping Carts', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCarts' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Catalog', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCatalog' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Products', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminProducts' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Categories', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCategories' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Monitoring', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminTracking' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Attributes & Features', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentAttributesGroups' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Attributes', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAttributesGroups' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Features', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminFeatures' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Brands & Suppliers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentManufacturers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Brands', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminManufacturers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Suppliers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSuppliers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Files', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAttachments' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Discounts', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentCartRules' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Cart Rules', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCartRules' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Catalog Price Rules', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSpecificPriceRule' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stock', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockManagement' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentCustomer' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCustomers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Addresses', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAddresses' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Outstanding', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminOutstanding' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customer Service', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentCustomerThreads' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customer Service', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCustomerThreads' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Order Messages', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminOrderMessage' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Merchandise Returns', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminReturn' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stats', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStats' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Warehouses', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminWarehouses' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stock Management', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentStockManagement' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stock Management', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockManagement' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stock Movement', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockMvt' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Instant Stock Status', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockInstantState' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stock Coverage', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockCover' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Supply orders', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSupplyOrders' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Configuration', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStockConfiguration' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Improve', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='IMPROVE' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Modules', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentModulesSf' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Module Manager', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesSf' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Modules', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesManage' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Alerts', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesNotifications' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Updates', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesUpdates' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Module Catalog', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentModulesCatalog' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Module Catalog', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesCatalog' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Module Selections', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAddonsCatalog' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Design', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentThemes' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Theme & Logo', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminThemes' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Theme Catalog', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminThemesCatalog' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Email Theme', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentMailTheme' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Email Theme', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminMailTheme' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Pages', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCmsContent' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Positions', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminModulesPositions' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Image Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminImages' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Shipping', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentShipping' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Carriers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCarriers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Preferences', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminShipping' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Payment', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentPayment' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Payment Methods', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminPayment' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Preferences', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminPaymentPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='International', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminInternational' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Localization', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentLocalization' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Localization', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminLocalization' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Languages', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminLanguages' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Currencies', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCurrencies' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Geolocation', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminGeolocation' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Locations', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentCountries' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Zones', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminZones' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Countries', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCountries' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='States', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStates' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Taxes', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentTaxes' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Taxes', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminTaxes' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Tax Rules', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminTaxRulesGroup' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Translations', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminTranslations' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Configure', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='CONFIGURE' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Shop Parameters', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='ShopParameters' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='General', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='General', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Maintenance', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminMaintenance' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Order Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentOrderPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Order Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminOrderPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Statuses', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStatuses' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Product Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminPPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customer Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentCustomerPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Customer Settings', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminCustomerPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Groups', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminGroups' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Titles', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminGenders' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Contact', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentStores' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Contacts', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminContacts' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Stores', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminStores' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Traffic & SEO', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentMeta' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='SEO & URLs', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminMeta' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Search Engines', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSearchEngines' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Referrers', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminReferrers' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Search', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentSearchConf' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Search', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminSearchConf' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Tags', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminTags' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Advanced Parameters', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAdvancedParameters' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Information', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminInformation' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Performance', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminPerformance' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Administration', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAdminPreferences' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='E-mail', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminEmails' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Import', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminImport' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Team', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentEmployees' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Employees', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminEmployees' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Profiles', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminProfiles' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Permissions', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminAccess' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Database', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminParentRequestSql' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='SQL Manager', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminRequestSql' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='DB Backup', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminBackup' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Logs', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminLogs' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Webservice', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminWebservice' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Multistore', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminShopGroup' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Multistore', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminShopUrl' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Experimental Features', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminFeatureFlag' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Quick Access', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminQuickAccesses' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='More', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='DEFAULT' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Link List', `wording_domain`='Modules.Linklist.Admin' WHERE `class_name`='AdminLinkWidget' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';
UPDATE `PREFIX_tab` SET `wording`='Theme & Logo', `wording_domain`='Admin.Navigation.Menu' WHERE `class_name`='AdminThemesParent' AND COALESCE(`wording`, '') = '' AND COALESCE(`wording_domain`, '') = '';

INSERT IGNORE INTO `PREFIX_configuration` (`id_shop_group`, `id_shop`, `name`, `value`, `date_add`, `date_upd`)
SELECT `id_shop_group`, `id_shop`, 'PS_LOGS_EMAIL_RECEIVERS', `value`, `date_add`, `date_upd` FROM `PREFIX_configuration` WHERE `name` = 'PS_SHOP_EMAIL';
