SET SESSION sql_mode='';
SET NAMES 'utf8mb4';

/* Normalize database text field sizes on all installs - see https://github.com/PrestaShop/PrestaShop/pull/35749 */
ALTER TABLE `PREFIX_address` CHANGE `other` `other` MEDIUMTEXT;
ALTER TABLE `PREFIX_attachment_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_cart_rule` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_cart` CHANGE `delivery_option` `delivery_option` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_cart` CHANGE `gift_message` `gift_message` MEDIUMTEXT;
ALTER TABLE `PREFIX_cart` CHANGE `checkout_session_data` `checkout_session_data` MEDIUMTEXT NULL;
ALTER TABLE `PREFIX_category_lang` CHANGE `additional_description` `additional_description` MEDIUMTEXT;
ALTER TABLE `PREFIX_category_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_cms_category_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_cms_lang` CHANGE `content` `content` longtext;
ALTER TABLE `PREFIX_configuration_kpi_lang` CHANGE `value` `value` MEDIUMTEXT;
ALTER TABLE `PREFIX_configuration_kpi` CHANGE `value` `value` MEDIUMTEXT;
ALTER TABLE `PREFIX_configuration_lang` CHANGE `value` `value` MEDIUMTEXT;
ALTER TABLE `PREFIX_configuration` CHANGE `value` `value` MEDIUMTEXT;
ALTER TABLE `PREFIX_contact_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_customer_message` CHANGE `message` `message` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_customer` CHANGE `note` `note` MEDIUMTEXT;
ALTER TABLE `PREFIX_hook` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_import_match` CHANGE `match` `match` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_log` CHANGE `message` `message` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_manufacturer_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_manufacturer_lang` CHANGE `short_description` `short_description` MEDIUMTEXT;
ALTER TABLE `PREFIX_message` CHANGE `message` `message` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_order_detail` CHANGE `product_name` `product_name` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_order_invoice` CHANGE `note` `note` MEDIUMTEXT;
ALTER TABLE `PREFIX_order_invoice` CHANGE `shop_address` `shop_address` MEDIUMTEXT DEFAULT NULL;
ALTER TABLE `PREFIX_order_message_lang` CHANGE `message` `message` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_order_return` CHANGE `question` `question` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_orders` CHANGE `gift_message` `gift_message` MEDIUMTEXT;
ALTER TABLE `PREFIX_orders` CHANGE `note` `note` MEDIUMTEXT;
ALTER TABLE `PREFIX_product_lang` CHANGE `description_short` `description_short` MEDIUMTEXT;
ALTER TABLE `PREFIX_product_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_request_sql` CHANGE `sql` `sql` MEDIUMTEXT NOT NULL;
ALTER TABLE `PREFIX_store_lang` CHANGE `hours` `hours` MEDIUMTEXT;
ALTER TABLE `PREFIX_store_lang` CHANGE `note` `note` MEDIUMTEXT;
ALTER TABLE `PREFIX_supplier_lang` CHANGE `description` `description` MEDIUMTEXT;
ALTER TABLE `PREFIX_webservice_account` CHANGE `description` `description` MEDIUMTEXT NULL;
