name: JS tests
on: [push, pull_request]
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  js-tests:
    name: JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        run:
          npm ci --prefix ./_dev

      - name: Launch typescript linter
        run:
          npm run test --prefix ./_dev
  js-linter:
    name: JS linter syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        run:
          npm ci --prefix ./_dev

      - name: Launch typescript linter
        run: |
          npm run lint --prefix ./_dev || {
            echo "::error::ESLint check failed. Run 'npm run lint:fix' to autofix issues."
            exit 1
          }
